# Generated by Django 6.0.1 on 2026-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(max_length=1000, verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, upload_to="image/", verbose_name="Изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                ("publication", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("counter_views", models.IntegerField(null=True, verbose_name="количество просмотров")),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["title"],
            },
        ),
    ]
