# Generated by Django 6.0.1 on 2026-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="counter_views",
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="количество просмотров"),
        ),
    ]
