# Generated by Django 6.0.1 on 2026-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/", verbose_name="Изображение"),
        ),
    ]
