# Generated by Django 6.0.1 on 2026-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение в формате JPEG или PNG, не более 5 МБ",
                null=True,
                upload_to="image/",
                verbose_name="Изображение",
            ),
        ),
    ]
