# Generated by Django 4.2.2 on 2026-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_category_id_alter_contact_id_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status_publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
